# Copyright (c) 2025 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

arkweb_device_fido_ext_sources = get_path_info([
    "authenticator_credential_response_extra_common.h",
    "ctap_get_assertion_request_extra.h",
    "ctap_make_credential_request_extra.h",
    "ctap_request_extra_common.h",
    "ohos/fido2_api.h",
    "ohos/ohos_authenticator.cpp",
    "ohos/ohos_authenticator.h",
    "ohos/ohos_fido_discovery.cpp",
    "ohos/ohos_fido_discovery.h",
    "ohos/ohos_webauthn_api.cpp",
    "ohos/ohos_webauthn_api.h",
    "ohos/type_conversions.cpp",
    "ohos/type_conversions.h",
    "ohos/fido2_api_utils.cpp",
    "ohos/fido2_api_utils.h",
  ], "abspath")
