# Copyright (c) 2025 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import("//build/config/ohos/config.gni")
arkweb_media_gpu_ohos_sources = [
      "//arkweb/chromium_ext/media/gpu/ohos/codec_allocator.cc",
      "//arkweb/chromium_ext/media/gpu/ohos/codec_allocator.h",
      "//arkweb/chromium_ext/media/gpu/ohos/codec_buffer_wait_coordinator.cc",
      "//arkweb/chromium_ext/media/gpu/ohos/codec_buffer_wait_coordinator.h",
      "//arkweb/chromium_ext/media/gpu/ohos/codec_image.cc",
      "//arkweb/chromium_ext/media/gpu/ohos/codec_image.h",
      "//arkweb/chromium_ext/media/gpu/ohos/codec_output_buffer_renderer.cc",
      "//arkweb/chromium_ext/media/gpu/ohos/codec_output_buffer_renderer.h",
      "//arkweb/chromium_ext/media/gpu/ohos/codec_surface_bundle.cc",
      "//arkweb/chromium_ext/media/gpu/ohos/codec_surface_bundle.h",
      "//arkweb/chromium_ext/media/gpu/ohos/codec_wrapper.cc",
      "//arkweb/chromium_ext/media/gpu/ohos/codec_wrapper.h",
      "//arkweb/chromium_ext/media/gpu/ohos/direct_shared_image_video_provider.cc",
      "//arkweb/chromium_ext/media/gpu/ohos/direct_shared_image_video_provider.h",
      "//arkweb/chromium_ext/media/gpu/ohos/pooled_shared_image_video_provider.cc",
      "//arkweb/chromium_ext/media/gpu/ohos/pooled_shared_image_video_provider.h",
      "//arkweb/chromium_ext/media/gpu/ohos/frame_info_helper.cc",
      "//arkweb/chromium_ext/media/gpu/ohos/frame_info_helper.h",
      "//arkweb/chromium_ext/media/gpu/ohos/ohos_video_decoder.cc",
      "//arkweb/chromium_ext/media/gpu/ohos/ohos_video_decoder.h",      
      "//arkweb/chromium_ext/media/gpu/ohos/ohos_video_encode_accelerator.cc",
      "//arkweb/chromium_ext/media/gpu/ohos/ohos_video_encode_accelerator.h",
      "//arkweb/chromium_ext/media/gpu/ohos/shared_image_video_provider.cc",
      "//arkweb/chromium_ext/media/gpu/ohos/shared_image_video_provider.h",
      "//arkweb/chromium_ext/media/gpu/ohos/video_frame_factory.h",
      "//arkweb/chromium_ext/media/gpu/ohos/video_frame_factory_impl.cc",
      "//arkweb/chromium_ext/media/gpu/ohos/video_frame_factory_impl.h",
      "//arkweb/chromium_ext/media/gpu/ohos/ohos_image_decode_accelerator_worker.cc",
      "//arkweb/chromium_ext/media/gpu/ohos/ohos_image_decode_accelerator_worker.h",
      "//arkweb/chromium_ext/media/gpu/ohos/ohos_image_decoder.cc",
      "//arkweb/chromium_ext/media/gpu/ohos/ohos_image_decoder.h",
      "//arkweb/chromium_ext/media/gpu/ohos/ohos_heif_image_decoder.cc",
      "//arkweb/chromium_ext/media/gpu/ohos/ohos_heif_image_decoder.h",
]